### PR TITLE
Suggest solution if add-apt-repository is not installed

### PR DESCRIPTION
**Pull request by leliamesteban**

### CODE REVIEW

**Comment by kgilmer** [comment]
I did not get a notification of this PR @leliamesteban .  Thank you for the addition!  I will review shortly.

**Comment by kgilmer** [comment]
In order to keep the root page concise, I'd prefer to roll your fix suggestion into the troubleshooting page and make the previous note more generic to cover any installation issue.  What do you think?

**Comment by leliamesteban** [comment]
Absolutely, I just wanted to call attention to the issue, so the user
experience matches with the tutorial. How you write it is of course up to
you.

**Comment by kgilmer** [comment]
Your help content has been added to the troubleshooting page @leliamesteban .  Thank you for your contribution!

**Pull request closed without merging**
